name: Docker

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Compose Containers
      run: docker compose up -d --build --remove-orphans

    - name: Run Make Clean
      run: docker exec chess make clean

    - name: Run Make
      run: docker exec chess make

# TODO: run tests instead
    - name: Run Chess
      run: docker exec chess ./out/chess

    - name: Run Make Clean
      run: docker exec chess make clean

    - name: Stop containers
      if: always()
      run: docker compose down
