name: Docker

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - main

jobs:
  docker:
    # timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Compose Containers
      run: docker compose -f up -d --build

    - name: Stop containers
      if: always()
      run: docker compose -f down
