name: Hourly Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Start Script
        run: ./scripts/start.sh

      - name: Run Tests in Docker Container
        run: docker exec chess /bin/bash -c "./scripts/test.sh --valgrind"

      - name: Stop containers
        if: always()
        run: docker compose down
